import type { Metadata } from "next";
import "./globals.css";
// import { ThemeProvider } from "@/components/ui/theme-provider";
import NavigationMenu from "../components/navigation-menu";
import LoggedOutLayout from "./(logged-out)/layout";
import LoggedInLayout from "./(logged-in)/layout";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

        {/* <LoggedInLayout>{children}</LoggedInLayout> */}
        <LoggedInLayout>{children}</LoggedInLayout>

      </body>
    </html>
  );
}
